#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Thrift
  module Test
    class Foo
      include ::Thrift::Struct, ::Thrift::Struct_Union
      ID = 1
      COUNT = 2
      NAME = 3
      DELETED = 4

      FIELDS = {
        ID => {:type => ::Thrift::Types::I64, :name => 'id'},
        COUNT => {:type => ::Thrift::Types::I32, :name => 'count', :optional => true},
        NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
        DELETED => {:type => ::Thrift::Types::BOOL, :name => 'deleted'}
      }

      def struct_fields; FIELDS; end

      def validate
        raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field id is unset!') unless @id
      end

      ::Thrift::Struct.generate_accessors self
    end

    class FooException < ::Thrift::Exception
      include ::Thrift::Struct, ::Thrift::Struct_Union
      TYPE = 1
      MESSAGE = 2

      FIELDS = {
        TYPE => {:type => ::Thrift::Types::I32, :name => 'type'},
        MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
end
